### ISSUE TITLE
HTTP 500 by first site visit

### ISSUE THREAD

**Issue by m4ntic0r** [Chevereto/Chevereto-Free#32] opened 2018-04-20 11:43 UTC
I have a problem with the upgrade from chevereto free 1.0.9 to latest 1.0.10
Everything is working fine, but if i upgrade to 1.0.10 every time i restart the browser and go to my-domain.de/chevereto i get a blank page with HTTP 500. When i press F5 chevereto loads normal. Tried Firefox/Chrome/IE. Its always the same problem. Went back to 1.0.9 and all is ok.

Did the update again, and the problem is there again. Only HTTP 500 when i first visit the webpage. I have a nginx reverse proxy, but even when i directly go to the server with ip/chevereto the problem is there.. its a standard debian 9/apache/php/mariadb with latest package versions.

On version 1.0.9 there is not such a problem?

**Comment by rodolfoberrios** [comment] 2018-04-20 13:38
Enable debug and show that output

**Comment by m4ntic0r** [comment] 2018-04-20 15:01
i changed debug_level to 3, but where can i found the entries or log file?

**Comment by rodolfoberrios** [comment] 2018-04-20 15:03
Your server error_log file

**Comment by m4ntic0r** [comment] 2018-04-20 15:15
there are no helpful entries in /var/log/apache2/error.log

you can try out: https://mm-vault.de/chevereto

when you press F5, site should load

**Comment by rodolfoberrios** [comment] 2018-04-20 15:29
Maybe you are supressing the built-in php error reporting system. Check your server.

Please keep in mind that I'm unable to review this issue if you don't provide any log entry. Browsing your website throws me the error, but it doesn't tell me anything about it.

**Comment by m4ntic0r** [comment] 2018-04-20 15:54
Hm i enabled all error log settings in php.ini but there is not a single entry about chevereto.
I changed logging to a new log file, but there are no entries about chevereto, too
i dont know.. i use a default debian 9 install with default php settings, and there is no issue with 1.0.9

**Comment by rodolfoberrios** [comment] 2018-04-20 16:07
If you don't provide me a log entry or detect where the issue is then I can't help you. This software is forked from a previous stage of the paid edition and it inheriths everything from it, including outdated bugs like this.

Anytime you don't pay money for something you actually pay something in exchange. In this case, you get the software "as-is".

Why you don't just rollback to v1.0.9 ¯\_(ツ)_/¯ ?

**Comment by m4ntic0r** [comment] 2018-04-20 16:13
now i did the rollback to 1.0.9, and there is no problem.

i cannot provide any logs when there are no logs. Other errors are logged correctly. I have made multiple updates of chevereto free in the past without a problem.

i dont see any problems on my side. but thanks.

**Comment by biffhuxtable** [comment] 2018-04-20 16:14
I have this issue, also. Do you mind sharing how to roll back to 1.0.9?

**Comment by m4ntic0r** [comment] 2018-04-20 16:46
i use veeam backups and vmware snapshots

**Comment by mashirozx** [comment] 2018-04-21 02:49
The same problem

**Comment by mashirozx** [comment] 2018-04-21 03:30
@biffhuxtable 
1. Backup your current SQL DB (via phpMyAdmin or etc.)
2. Backup the `images/` directory, this is **important**!
3. Remove the old Chevereto Database
4. Remove or rename the old Chevereto folder
5. Reinstall Chevereto 1.0.9
6. After reinstall clean the database again, and import the database backup in first step

I did like above, and didn't meet any problem. 

@rodolfoberrios Seems the database structure & contents are completely the same in these two version?

**Comment by rodolfoberrios** [comment] 2018-04-21 04:35
Did someone tried using the js from the paid edition? I can recall that this was related to the drag select functionality.

https://demo.chevereto.com/app/lib/chevereto.js

**Comment by m4ntic0r** [comment] 2018-04-21 09:06
i tried with this chevereto.js, but problem is still there

**Comment by rodolfoberrios** [comment] 2018-04-22 02:07
Fixed on v1.0.11

**Closed by rodolfoberrios** 2018-04-22 02:07 UTC

**Comment by m4ntic0r** [comment] 2018-04-22 08:52
Thanks for your fast support on this free edition. Its working now.
Great product.
